### ISSUE TITLE
Wrong value range

### ISSUE THREAD

**Issue by hugo419752** [phifogg/ioBroker.sainlogic#262]
Hi, after updating to the new version 1.0.14 there is a bug with the value range of the newly added distance sensor.
The three Values that would be read are "air_ch" "depth_ch" "thi_ch"

The bug is, that the current values are greater than the assumed values. 
I don't know why there is a range for these values. But mine ar absolutely fine and I think there should no range be defined for these three values.

<html>
<body>

sainlogic.0 | 2025-12-27 11:51:30.306 | warn | State value to set for "sainlogic.0.weather.current.1.thi_ch" has value "1795" greater than max "500"

-- | -- | -- | --
sainlogic.0 | 2025-12-27 11:51:30.305 | warn | State value to set for "sainlogic.0.weather.current.1.air_ch" has value "602" greater than max "500"

sainlogic.0 | 2025-12-27 11:50:30.391 | warn | State value to set for "sainlogic.0.weather.current.1.depth_ch" has value "1193" greater than max "5"

</body>
</html> 

 - Adapter version: 1.0.14
 - JS-Controller version: 7.0.7
 - Node version: 20.19.5
 - Operating system: linux

**Comment by phifogg** [comment]
Fixed in 1.1.1.
You can install directly from github or wait till stable release gets updated (about 1 week from now).

**Comment by mcm1957** [comment]
@phifogg THANKS for fast fix!

I would like to add some Info:

Installation from Github is not recommended for normal use cases, especially at production systems.
Release 1.1.1 can already by installed FROM npm (not with npm) by using "von npm installieren" (Expertmode on) NOW
Release 1.1.1 can be installed from LATEST repository tomorrow latest

**Comment by hugo419752** [comment]
Hello, after updating to 1.1.1 i still have the same problems...


<html>
<body>

sainlogic.0 | 2026-01-05 12:08:43.310 | warn | State value to set for "sainlogic.0.weather.current.1.depth_ch" has value "1193" greater than max "5"
-- | -- | -- | --
sainlogic.0 | 2026-01-05 12:08:43.309 | warn | State value to set for "sainlogic.0.weather.current.1.thi_ch" has value "1795" greater than max "500"
sainlogic.0 | 2026-01-05 12:08:43.309 | warn | State value to set for "sainlogic.0.weather.current.1.air_ch" has value "602" greater than max "500"


</body>
</html>

**Comment by phifogg** [comment]
Can you delete that data point in iobroker so that the adapter will re-create it?
